language: python
dist: trusty
sudo: false

addons:
  apt:
    packages:
    - nco


python:
  - "3.6"

install:
  - pip install --upgrade pip
  - pip install netcdf4 scipy
  - pip freeze

script:
  - make
